# Generated by Django 4.2 on 2024-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/default.jpg', null=True, upload_to='profile/profile_pics', verbose_name='Image'),
        ),
    ]
