# Generated by Django 4.2 on 2024-07-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile/images/default.jpg', null=True, upload_to='profile/images', verbose_name='Image'),
        ),
    ]
