version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      

volumes:
  postgres-data:
