version: "3.8"
services:
  backend:
    volumes:
      - static:/static
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    expose:
      - 8000
    networks:
      - dev-network
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - 80:80
    tty: true
    restart: "on-failure"
    depends_on:
      - backend
    networks:
      - dev-network
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - dev-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - dev-network
      
volumes:
  static:

networks:
  dev-network:
      driver: bridge