# Generated by Django 4.2 on 2024-07-09 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_id', models.CharField(max_length=100, verbose_name='Coin id')),
                ('coin_name', models.CharField(max_length=100, verbose_name='Coin name')),
                ('coin_symbol', models.CharField(default='backend/basic_info/images/metamask.png', max_length=100, verbose_name='Coin symbol')),
                ('coin_image', models.CharField(default='backend/basic_info/images/metamask.png', max_length=500, verbose_name='Coin image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'Crypto currency',
                'verbose_name_plural': 'Crypto currencie',
            },
        ),
    ]
