# Generated by Django 4.2 on 2024-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticketcontent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcontent',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tracking_code',
            field=models.CharField(editable=False, max_length=13, null=True),
        ),
    ]
