# Generated by Django 4.2 on 2024-06-10 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is_show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Digitalcurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is show?')),
            ],
            options={
                'verbose_name': 'Digital Currency',
                'verbose_name_plural': 'Digital currencies',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is_show')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='basic_info.country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
