# Generated by Django 5.0.6 on 2024-06-22 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('flag', models.CharField(max_length=200, verbose_name='Flag')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is_show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin_id', models.CharField(max_length=100, verbose_name='Coin id')),
                ('coin_name', models.CharField(max_length=100, verbose_name='Coin name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
            ],
            options={
                'verbose_name': 'Crypto currency',
                'verbose_name_plural': 'Crypto currencie',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=100, verbose_name='Wallet')),
                ('wallet_name', models.CharField(max_length=100, verbose_name='Wallet name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website_url', models.URLField(verbose_name='Website url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='wallet/logos/', verbose_name='Logo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='wallet/ qrcodes/', verbose_name='QR code')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('is_show', models.BooleanField(default=True, verbose_name='Is_show')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='basic_info.country', verbose_name='Country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
