# Generated by Django 5.0.6 on 2024-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='coin_image',
            field=models.CharField(default='backend/basic_info/images/metamask.png', max_length=500, verbose_name='Coin image'),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='coin_symbol',
            field=models.CharField(default='backend/basic_info/images/metamask.png', max_length=100, verbose_name='Coin symbol'),
        ),
    ]
