# Generated by Django 4.2 on 2024-06-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(default=1, max_length=200, verbose_name='Flag'),
            preserve_default=False,
        ),
    ]
