# Generated by Django 5.0.6 on 2024-06-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='tssssitle',
        ),
        migrations.AddField(
            model_name='state',
            name='title',
            field=models.CharField(default='nothing', max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='basic_info.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='state',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='basic_info.city'),
        ),
    ]
