# Generated by Django 4.2 on 2024-06-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_country_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalcurrency',
            name='is_show',
        ),
        migrations.RemoveField(
            model_name='digitalcurrency',
            name='name',
        ),
        migrations.AddField(
            model_name='digitalcurrency',
            name='coin_id',
            field=models.CharField(default=1, max_length=100, verbose_name='Coin id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalcurrency',
            name='coin_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Coin name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='digitalcurrency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
    ]
