# Generated by Django 5.0.6 on 2024-06-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_cryptocurrency_coin_image_cryptocurrency_coin_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
