# Generated by Django 4.2 on 2024-07-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_delete_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
    ]
