# Generated by Django 4.2 on 2024-06-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_remove_digitalcurrency_is_show_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digitalcurrency',
            new_name='CryptoCurrency',
        ),
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name': 'Crypto currency', 'verbose_name_plural': 'Crypto currencie'},
        ),
    ]
