# Generated by Django 4.2 on 2024-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_rename_digitalcurrency_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='coin_image',
            field=models.CharField(default=1, max_length=100, verbose_name='Coin image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='coin_symbol',
            field=models.CharField(default=1, max_length=100, verbose_name='Coin symbol'),
            preserve_default=False,
        ),
    ]
