# Generated by Django 4.2 on 2024-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0005_cryptocurrency_coin_image_cryptocurrency_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='coin_image',
            field=models.CharField(max_length=500, verbose_name='Coin image'),
        ),
    ]
